// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkjrorhzuivndtrvdeoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhranJvcmh6dWl2bmR0cnZkZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDE1MzQsImV4cCI6MjA2NDI3NzUzNH0.yQNFxo93KKZ9NLuxQBUwxl2vzr2QnQYo-4cARw5hpQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);