
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjrwdjuzkjnvisaxdkmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcndkanV6a2pudmlzYXhka21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjgzNDYsImV4cCI6MjA2NDcwNDM0Nn0.AE4zlXI2myXucdpIqraGtgGjtzR2PAdmC29WmZk7jVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
